Coalculator MVP
jensdreske/capstone-project pull request #8
Opened 2021-06-20 21:37 UTC by jensdreske

Please have a look at my "Coalculator" App. It calculates CO2 Emissions and should feel like a game. 
You can set a goal for CO2 Emission savings (in the near future, still hardcoded ) and change the behavior in different areas to reach it.
The main page shows the shares of different emission contributing areas. 
Right now one can click on the Transportation area, make some changes to the average German Citizen and get some calculations - your score-  instantly updated in the footer area.
Any suggestions appreciated

2021-06-22 09:50 UTC, ThomasKirst requested changes
Overall quite complex structure. Consider writing a few unit tests for your math calculations.

Following linter issues have been detected:

```

/Users/thomas/Development/neuefische/2021-w2/_student_projects/coalculator/client/src/App.js
   2:25  warning  'NavLink' is defined but never used                       no-unused-vars
  16:28  warning  'setCountryEmissions' is assigned a value but never used  no-unused-vars
  20:28  warning  'setCountryDataState' is assigned a value but never used  no-unused-vars

/Users/thomas/Development/neuefische/2021-w2/_student_projects/coalculator/client/src/components/Footer.js
  45:11  warning  'daysLeft' is assigned a value but never used  no-unused-vars

/Users/thomas/Development/neuefische/2021-w2/_student_projects/coalculator/client/src/components/Shares.js
   9:8   warning  'car' is defined but never used                                                                            no-unused-vars
  11:8   warning  'house' is defined but never used                                                                          no-unused-vars
  62:17  warning  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

/Users/thomas/Development/neuefische/2021-w2/_student_projects/coalculator/client/src/components/SharesUnfcc.js
   2:10  warning  'NavLink' is defined but never used                                                                              no-unused-vars
  24:6   warning  React Hook useEffect has a missing dependency: 'getEmissions'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/Users/thomas/Development/neuefische/2021-w2/_student_projects/coalculator/client/src/components/carbonApiCheck.js
  1:10  warning  'useEffect' is defined but never used  no-unused-vars

/Users/thomas/Development/neuefische/2021-w2/_student_projects/coalculator/client/src/pages/Transportation.js
   8:10  warning  'CarbonApiCheck' is defined but never used                                                                                     no-unused-vars
  24:6   warning  React Hook useEffect has a missing dependency: 'recalculateIndividualScore'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

✖ 12 problems (0 errors, 12 warnings)
```

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +    const co2BudgetLeft = 3.5;
Are these kgs, gigatons, photons? ;)

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +  }
These calculations should be enclosed within functions which ideally are tested by unit tests.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +    if (years > 1000) return "Never";
Could this `guard` be joined with the first if statement?

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +    const daysLeft = days % 365;
`daysLeft` is unused. Please remove.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +*/}
Remove comment.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +      <GameScores scrollPosition={scrollPos} setScrollPos={setScrollPos} />
Props should be named consistently: pos vs. position

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +          {/* <div className={"scoreBoxes " + "score" + scrollPosition} > */}
Remove comment.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +    animation-duration: 2s; */
Remove comment.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Footer.js
> +  } */
Remove comment.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Header.js
> +        <img className="cloudlet" src={cloudlet} alt="cloudlet" />
Please add the width and height attributes to the image tags.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Header.js
> +  /* border: 1px solid red; */
Remove comment.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Shares.js
> +  const [infoVisible, setInfoVisible] = useState([]);
Move state to the beginning of the function.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Shares.js
> +  });
Does this code block do anything that it is used later on?

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Shares.js
> +          }
Could this function be extracted so it is not declared in each loop?

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Shares.js
> +                <Tooltip className="tooltipText">
StyledComponent: why an additional className?

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Shares.js
> +                <SliceText className={infoVisible[index] ? "show" : "hide"}>
StyledComponent with additional className? Might be better to work with props that are passed into the StyledComponent.
`<SliceText className={infoVisible[index] ? "show" : "hide"}>`
–> `<SliceText isVisible={infoVisible[index]} />`

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/Shares.js
> +`;
Comments over comments!

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/components/carbonApiCheck.js
> +  function getCar() {
What exactly happens here? Is there a better name to describe this function?

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/pages/Transportation.js
> +const playerTransport = JSON.stringify(player.transport);
```suggestion
const playerTransport = {...player.transport}; // check if it deeply copies all properties
```

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/pages/Transportation.js
> +      transport: { ...JSON.parse(playerTransport) },
Might be obsolete with the former change.

2021-06-22 09:50 UTC, ThomasKirst commented on client/src/pages/Transportation.js
> +  });
Move into an `initialState` constant since it's going to be used again in `resetForm()`.

2021-06-22 22:21 UTC, jensdreske commented on client/src/pages/Transportation.js
> +      transport: { ...JSON.parse(playerTransport) },
somehow not, spreading does not work for me here. 
The reset button does not work, if I try.

2021-06-23 08:50 UTC, jensdreske commented on client/src/pages/Transportation.js
> +      transport: { ...JSON.parse(playerTransport) },
The spread operator makes deep copies of data if the data is not nested. When you have nested data in an array or object the spread operator will create a deep copy of the top most data and a shallow copy of the nested data.

[the-spread-operator-deep-and-shallow-copies](https://medium.com/@kevinlai76/the-spread-operator-deep-and-shallow-copies-d193ac9b58bf)

2021-06-23 10:11 UTC, anitaschiller requested changes
Hi Jens, good job, just some small remarks :-)

2021-06-23 10:11 UTC, anitaschiller commented on client/src/pages/Transportation.js
> +          ((player.transport[vehicle].consumption / 100) *
You could consider extracting these calculations in a lib folder so that the domain/business logic does not "pollute" the UI component.

2021-06-23 11:36 UTC, jensdreske commented on client/src/pages/Transportation.js
> +          ((player.transport[vehicle].consumption / 100) *
check. good one! code looks cleaner now

2021-06-24 12:12 UTC, anitaschiller approved these changes
Well done, Jens, approved! :)

2021-06-24 17:18 UTC, merged